In [1]:
import numpy as np

## Definitions
**Rank**: the number of dimensions in an array/matrix/tensor
**Shape**: the number of items in each dimension

## Arrays

In [76]:
# create an array
print("an array: ")
print(np.array([[1,2,3],[4,5,6]]))

print("\nnp.zeros: ")
print(np.zeros((2,2)))

print("\nnp.empty_like: ")
print(np.empty_like(np.array([1,2,3])))

print("\nnp.ones: ")
print(np.ones((3,2)))

print("\nnp.full: ")
print(np.full((2,3),7))

print("\nnp.eye: ")
print(np.eye(2))

print("\nnp.random: ")
print(np.random.random((2,4)))

print("\nnp.tile: ")
v = np.array([1, 0, 1])
print("v = ", v)
vv = np.tile(v, (4,1))
print("vv = ")
print(vv)

an array: 
[[1 2 3]
 [4 5 6]]

np.zeros: 
[[ 0.  0.]
 [ 0.  0.]]

np.empty_like: 
[0 0 0]

np.ones: 
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]

np.full: 
[[7 7 7]
 [7 7 7]]

np.eye: 
[[ 1.  0.]
 [ 0.  1.]]

np.random: 
[[ 0.52204181  0.63009598  0.9737873   0.55359553]
 [ 0.24787432  0.52469549  0.48031071  0.2089254 ]]

np.tile: 
('v = ', array([1, 0, 1]))
vv = 
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


## Slicing and indexing

- a[1:3] gives item 1 and 2 (not 3)

#### When slicing, numpy returns a lower-rank object
- if you index a column id and slice that column, you get a row array back
- same if you index and slice a row
- the shape of these will be identical

In [24]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print("slice a row: ")
print(a[1,:])

print("\nslice a column: ")
print(a[:,2])

slice a row: 
[5 6 7 8]

slice a column: 
[ 3  7 11]


#### When indexing, you can arbitrarily combine the data in different ways
- the following selects the 0th, 1st, and 2nd row and the 0th, 1st and 0th item from these, respectively:

In [49]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[ 0, 1, 2], 
        [0, 1, 0]])

print("\nis equivalent to indexing individual elements: ")
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

print("\nand you can have arbitrary shapes: ")
print(a[[ [0],[1],[2] ],
        [ [0],[1],[0] ]])

[1 4 5]

is equivalent to indexing individual elements: 
[1 4 5]

and you can have arbitrary shapes: 
[[1]
 [4]
 [5]]


### Mutate one element

In [55]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 1, 0])

# Select one element from each row of a using the indices in b
print("\nlet's add 10 to the following elements: ")
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print("\nnow A is: ")
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

let's add 10 to the following elements: 
[ 1  6  8 10]

now A is: 
[[11  2  3]
 [ 4  5 16]
 [ 7 18  9]
 [20 11 12]]


### Boolean array indexing
- can compare the entire numpy object to generate a same-shape object of Boolean values

In [56]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(a)
print("\n")
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]


[[False False]
 [ True  True]
 [ True  True]]


## Element-wise operations

#### Add: 
- can use x+y or np.add(x,y)

#### Subtract:
- can use x-y or np.subtract(x,y)

#### Multiply:
- can use x*y or np.multiply(x,y)

#### Divide:
- can use x/y or np.divide(x,y)

#### Square root:
- can use np.sqrt(x)

#### Matrix multiplication (dot product)
- For two arrays: can use a.dot(b) or np.dot(a,b)
- For matrix x and array v: can use x.dot(v) or np.dot(x,v)


In [65]:
x = np.array([[1,2],[3,4],[5,6]])

v = np.array([9,10])
x.dot(v)

array([ 29,  67, 105])

### Sum over all elements in row/column/matrix:

#### row
- np.sum(x, axis = 0) 

#### column
- np.sum(x, axis=1)

#### matrix
- np.sum(x)

### Broadcasting

#### If the arrays do not have the same rank, prepend lower ranked array with 1s
- x = np.array([[[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]])
- x.shape is (1,4,3)
- y = np.array([10,11,12])
- y.shape is (1,3) but becomes (1,1,3) for broadcasting

#### The two arrays are compatible in a dimension if the sizes match OR one of the sizes is 1
- x.shape is (1,4,3)
- y.shape for broadcasting is (1,1,3)
- compatible in all dimensions

#### Arrays can be broadcast if they are compatible in all dimensions

#### After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays
- x + y shape is (1,4,3)

#### Anywhere one array had size > 1 and the other had size = 1, smaller array was copied along larger array for that dimension

In [99]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4,1)) # Create an empty matrix with the same shape as x

print("x before adding v to each row: ")
print(x)
print(x.shape)
    
print("\nafter adding [1,0,1] to each row: ")
print(x+vv)

x before adding v to each row: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)

after adding [1,0,1] to each row: 
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [89]:
x = np.array([1,2,3,4])
print(x[:,np.newaxis])

[[1]
 [2]
 [3]
 [4]]


In [86]:
x[:,np.newaxis]+np.array([1,2,3])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [91]:
x = np.array([[[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]])
y = np.array([10,11,12])
print(x)
print(y)
print(x+y)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[10 11 12]
[[[11 13 15]
  [14 16 18]
  [17 19 21]
  [20 22 24]]]
